name: taming
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.13
  - pip=21.0.1
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.6.4
    - omegaconf==2.0.6
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - more-itertools>=8.0.0
    - transformers==4.11.3
    - torchmetrics==0.10.0
    - torch-fidelity==0.3.0
    - -e .
