model:
  base_learning_rate: 1.0e-06
  target: taming.modules.diffusionmodules.vq_diffusion.VQDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    image_size: 128
    channels: 3
    conditioning_key: cat_init
    monitor: val/loss_simple_ema
    ddim_timesteps: 200
    scheduler_config:
      target: taming.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 10000
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    loss_type: mixed
    unet_config:
      target: taming.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 128
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions:
        - 2
        - 4
        - 8
        - 16
        num_res_blocks: 1
        channel_mult:
        - 1
        - 2
        - 4
        - 8
        num_head_channels: 32
        use_spatial_transformer: false
        transformer_depth: 1
        context_dim: 32
    lpips_weight: 0.1
    encoder_config:
      target: taming.modules.diffusionmodules.model.VQEncoder
      params:
        embed_dim: 32
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,2,4]
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 32
    wrap: false
    train:
      target: taming.data.imagenet.ImageNetTrain
      params:
        config:
          size: 128
    validation:

      target: taming.data.imagenet.ImageNetValidation
      params:
        config:
          size: 128


lightning:
  trainer:
    max_steps: 200000
    gpus: 1
    val_check_interval: 1.0
    log_every_n_steps: 100
    num_sanity_val_steps: 0
    limit_val_batches: 25
